CREATE DATABASE NEWTEST
ON(
NAME = NEWTEST,
FILENAME='E:\MSSQL\SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\NEWTEST.MDF',
SIZE = 5MB,
MAXSIZE = 10MB,
FILEGROWTH=2MB
)
LOG ON(
NAME = NEWTEST_LOG,
FILENAME='E:\MSSQL\SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\NEWTEST_LOG.LDF',
SIZE = 3MB,
MAXSIZE = 8MB,
FILEGROWTH=2MB
)

ALTER DATABASE NEWTEST
ADD FILE (
NAME = USERS,
FILENAME='E:\MSSQL\SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\USERS.MDF',
SIZE = 3MB,
MAXSIZE = 7MB,
FILEGROWTH=2MB
)


ALTER DATABASE NEWTEST 
ADD LOG FILE(
NAME = USERS_LOG,
FILENAME='E:\MSSQL\SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\USERS_LOG.LDF',
SIZE = 3MB,
MAXSIZE = 7MB,
FILEGROWTH=2MB
)


ALTER DATABASE NEWTEST
MODIFY FILE(
NAME = USERS, --Logical Name
SIZE=10MB,
MAXSIZE=12MB
)

ALTER DATABASE NEWTEST
REMOVE FILE USERS --Lgical Name







